name: ipotato_timer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.16
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  uuid: ^4.0.0-beta1-1

dev_dependencies:
  build_runner: any
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
